config/routes.rb
Rails.application.routes.draw do
  root 'gossips#index'

    get 'gossips/index'
    get 'gossips/new'
    get 'gossips/show'
    post 'gossips/create'
    resources :gossips


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/gossip.rb
class Gossip < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController

  def new

  end

def create
  @gossip = Gossip.new(gossip_params)
@gossip.save
redirect_to @gossip
  end

  def show
    @gossip = Gossip.find(params[:id])
    puts "Ceci est mon commentaire: #{@gossip}"
  end

  def index

    @gossips = Gossip.all

  end


  private

    def gossip_params
      params.require(:gossips).permit(:anonymous_author, :content)
    end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/views/gossips/index.html.erb
<!DOCTYPE html>

<h1>Listing Gossips</h1>

<table>
  <tr>
    <th>Les Gossips</th>
    <th>Text</th>
  </tr>

  <% @gossips.each do |gossips| %>
    <tr>
      <td><%= gossips.anonymous_author %></td>
      <td><%= gossips.content %></td>
      <td><%= link_to 'Montrer la Gossip', gossip_path(gossips) %></td>
    </tr>
  <% end %>
</table>

app/views/gossips/new.html.erb
<!DOCTYPE html>

<h1>Les Gossips du groupe</h1>

<%= form_with scope: :gossips, url: gossips_path, local: true do |form| %>
  <p>
    <%= form.label :anonymous_author %><br>
    <%= form.text_field :anonymous_author %>
  </p>

  <p>
    <%= form.label :content %><br>
    <%= form.text_area :content %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/gossips/show.html.erb
<!DOCTYPE html>

<h2>Mon Gossip</h2>
<p><%= @gossip.content %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheGossipProject</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>